#!/usr/bin/env python3
"""Build the GitHub Pages demo (docs/) from the REAL web UI.

Renders web/templates/{index,login}.html with Jinja2 and copies the real CSS
and JavaScript, so the demo always looks and behaves like the product. The
only demo-specific code is docs/static/js/demo-api.js (+ demo.css), which
answers the UI's /api/... requests in the browser with simulated data.

Run after changing the web UI:   python3 scripts/build-demo.py
Needs Jinja2 (`pip install jinja2`, or python3-jinja2 / Flask installed).
"""
import shutil
import subprocess
import sys
import time
from pathlib import Path

try:
    from jinja2 import Environment, FileSystemLoader
except ImportError:
    sys.exit("Jinja2 is required: pip install jinja2  (or apt install python3-jinja2)")

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
DOCS = ROOT / "docs"

# Files copied verbatim from the real UI (the demo's own files are left alone)
COPY = ["static/css/style.css", "static/js/app.js", "static/js/liquid-glass.js"]

BANNER = ("<!-- GENERATED by scripts/build-demo.py from web/templates/{name} — "
          "do not edit by hand; edit the real UI and rebuild. -->\n")

# demo-api.js must run BEFORE app.js / liquid-glass.js: app.js calls the API
# as soon as it loads, and the demo replaces fetch() with its simulated backend.
DEMO_HEAD = '  <link rel="stylesheet" href="static/css/demo.css">\n'
DEMO_SCRIPT = '  <script src="static/js/demo-api.js"></script>\n'


def git_version():
    def git(*args):
        try:
            return subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True,
                                  text=True, check=True).stdout.strip()
        except (OSError, subprocess.CalledProcessError):
            return ""
    return {"commit": git("rev-parse", "--short", "HEAD") or "demo",
            "date": git("log", "-1", "--format=%cI") or time.strftime("%Y-%m-%d")}


def render(env, name, **ctx):
    html = env.get_template(name).render(**ctx)
    # inject the demo files, keeping everything else exactly as served
    if "</head>" not in html or '<script src="static/js/liquid-glass.js">' not in html:
        sys.exit(f"{name}: unexpected template structure — update build-demo.py")
    html = html.replace("</head>", DEMO_HEAD + "</head>", 1)
    html = html.replace('  <script src="static/js/liquid-glass.js">',
                        DEMO_SCRIPT + '  <script src="static/js/liquid-glass.js">', 1)
    # the real UI links to server routes; the static demo uses its own pages
    html = html.replace('href="/logout"', 'href="login.html"')
    html = html.replace('action="/login"', 'action="index.html"')
    return BANNER.format(name=name) + html


def main():
    env = Environment(loader=FileSystemLoader(str(WEB / "templates")), autoescape=True)
    env.globals["url_for"] = lambda endpoint, filename="": f"{endpoint}/{filename}"

    (DOCS / "index.html").write_text(
        render(env, "index.html", csrf_token="demo", version=git_version()), encoding="utf-8")
    (DOCS / "login.html").write_text(
        render(env, "login.html", csrf_token="", error=None), encoding="utf-8")

    for rel in COPY:
        dest = DOCS / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(WEB / rel, dest)

    for required in ("static/js/demo-api.js", "static/css/demo.css"):
        if not (DOCS / required).exists():
            sys.exit(f"missing docs/{required}")
    print(f"Demo built in {DOCS.relative_to(ROOT)}/ (index.html, login.html, {len(COPY)} assets)")


if __name__ == "__main__":
    main()
